---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  namespace: achyut
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-086eef36c0ad797ba
    fsType: ext4

#PVC:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
  namespace: achyut
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi


#Deployment with pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  namespace: achyut
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont-1
          image: nginx
          ports:
            - continerPort: 80
          volumeMounts:
            - mountPath: "/tmp/volumes"
              name: volume1
        - name: cont-2
          image: ubuntu
          command: ["/bin/bash", "-c","while true; do echo welcome; sleep 10; done"]
          volumeMounts:
            - mountPath: "/tmp/jenkins"
              name: volume1
      volumes:
        - name: volume1
          persistentVolumeClaim:
            claimName: pvc-1
