apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  selector:
    app: swiggy
  replicas: 2
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont2
          image: achyuty/web:streetfood
          ports:
            - containerPort: 80
