---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-rq
  namespace: dev
spec:
  hard:
    requests.cpu: "350m"
    limits.cpu: "700m"
    requests.memory: "75Mi"
    limits.memory: "150Mi"

#pod with limits
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod-1
  namespace: dev
spec:
  containers:
    - name: cont-1
      image: achyuty/web:tourism
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "10Mi"
        limits:
          cpu: "200m"
          memory: "15Mi"
